### ISSUE TITLE
GHC 8 Support

### ISSUE THREAD

**Issue by creichert** [scotty-web/wai-middleware-static#14]
A new stackage nightly is ready for GHC 8 (`nightly-2016-05-26`). `wai-middleware-static` was temporarily pulled from stackage for GHC 8 compatibility. 

Links for reference:
- https://github.com/fpco/stackage/blob/master/build-constraints.yaml#L2005
- https://www.fpcomplete.com/blog/2016/05/moving-stackage-nightly-ghc-8

Here is the first set of error messages I get trying to compile w/ the new resolver:

```
Resolver 'nightly-2016-05-26' does not have all the packages to match your requirements.
    expiring-cache-map not found
        - wai-middleware-static requires >=0.0.5 && <0.1
    hpc-coveralls not found
        - wai-middleware-static requires -any
```

**Comment by RyanGlScott** [comment]
Huh, I'm a bit perplexed that `wai-middleware-static` was blocked from a GHC 8.0 resolver, since I updated it a couple of days ago to be 8.0-compliant.

That being said, `hpc-coveralls` (on which `wai-middleware-static`'s test suite depends) doesn't currently build with GHC 8.0 ([`hpc-coveralls-1.0.4`](http://hackage.haskell.org/package/hpc-coveralls-1.0.4) has a restrictive upper bound on `transformers`), so perhaps this is blocked on `hpc-coveralls` being updated.

**Comment by RyanGlScott** [comment]
Sorry, `hpc-coveralls` isn't the problem, but rather its dependency `retry`, which has restrictive upper version bounds on `ghc-prim`. There's an open issue [here](https://github.com/Soostone/retry/issues/43).

**Comment by MichaelXavier** [comment]
Just a heads up, the relaxed upper bound has been released at 0.7.3. Let me know if you guys need anything else to unblock. Thanks!

**Comment by creichert** [comment]
@MichaelXavier @RyanGlScott Thanks a lot for the quick responses

**Comment by RyanGlScott** [comment]
Opened https://github.com/fpco/stackage/pull/1497 to add `wai-middleware-static` back to Stackage.

**Comment by RyanGlScott** [comment]
And now [it's back](https://github.com/fpco/stackage/commit/67e967988db6ef1afc7d885ed0b1806a98c2afe8) in Stackage.

**Comment by creichert** [comment]
@RyanGlScott Thanks again, very happy about this
